const { PrismaClient } = require('@prisma/client');
const { PrismaLibSql } = require('@prisma/adapter-libsql');

const adapter = new PrismaLibSql({ url: 'file:./dev.db' });
const prisma = new PrismaClient({ adapter });

async function main() {
  let user = await prisma.user.findFirst();
  if (!user) {
    console.error('No user found.');
    process.exit(1);
  }
  const userId = user.id;

  const movies = [
    {
      title: "Yi Yi",
      director: "Edward Yang",
      releaseYear: 2000,
      rating: 10,
      posterUrl: "https://image.tmdb.org/t/p/w500/jZJiNsOslG6iqoMj0YCBJ8ZLfJT.jpg",
      theGood: "A three-hour film about an ordinary family in Taipei that somehow contains all of human life",
      theBad: "The unhurried pacing and sprawling ensemble require patience and sustained attention",
      review: "Edward Yang's **Yi Yi** — the title means 'a one and a two,' a phrase musicians use to count in a song — is a film about everything. Birth, death, first love, marital exhaustion, professional ambition, childhood confusion, old age, adolescence, parenthood, loneliness, connection, the city, the self. It runs nearly three hours and not a minute is wasted.\n\nThe Jian family lives in a Taipei apartment. NJ (Wu Nien-jen), the father, is a middle-aged businessman confronting the emptiness of his professional life and the reappearance of a woman he loved thirty years ago. His wife Min-Min, after her mother's stroke, retreats to a Buddhist monastery to find meaning. Their teenage daughter Ting-Ting navigates her first romantic feelings. Their eight-year-old son Yang-Yang takes photographs of the backs of people's heads because, he explains, *you can't see that yourself*.\n\nYang-Yang's photographs are the film's thesis statement. We cannot see our own lives clearly while we're living them. We need art — cinema, photography, literature — to show us what we look like from behind, to reveal the parts of ourselves we can never directly observe.\n\n> \"Isn't life supposed to be more than what they teach you in school?\"\n\nYang shoots Taipei as a city of reflections. Characters appear doubled in glass, layered over the city's neon-lit streets. These reflections are not decorative; they are philosophical. Every person contains multiple selves. Every moment contains multiple possible meanings. Yang's camera captures this multiplicity with a patient, generous eye that judges no one.\n\nThe film's final sequence — Yang-Yang reading a letter to his deceased grandmother at her funeral — is one of the most emotionally overwhelming conclusions in cinema. The boy tells her he is sorry he couldn't show her all the things she couldn't see. He tells her he is old now. He is eight years old, and he is ancient, and Edward Yang films this paradox with a tenderness that makes you want to live more carefully.\n\nYang died of colon cancer in 2007 at fifty-nine. **Yi Yi** was his final film. It is, I believe, one of the ten greatest films ever made."
    },
    {
      title: "The Silence of the Lambs",
      director: "Jonathan Demme",
      releaseYear: 1991,
      rating: 9,
      posterUrl: "https://image.tmdb.org/t/p/w500/uS9m8OBk1RVfUPynBzfG8S1ENLz.jpg",
      theGood: "Anthony Hopkins created cinema's most indelible villain in barely sixteen minutes of screen time",
      theBad: "The film's treatment of gender identity through Buffalo Bill has been rightfully criticized",
      review: "Jonathan Demme's **The Silence of the Lambs** is the only horror film to win the Academy Award for Best Picture, and it earned the honor by being something more: a procedural thriller of extraordinary intelligence, a feminist narrative disguised as a genre film, and a showcase for two performances that redefined screen acting.\n\nJodie Foster's Clarice Starling is one of cinema's great protagonists — a young FBI trainee from a working-class background navigating a world of powerful men who alternately patronize, objectify, and underestimate her. Demme's camera frequently adopts her subjective viewpoint, with male characters staring directly into the lens, making the audience experience the discomfort of being constantly appraised. This technique transforms a serial killer thriller into a study of gendered power dynamics.\n\nAnthony Hopkins appears in the film for approximately sixteen minutes. In that time, he created the most iconic villain in cinema history. Hannibal Lecter — standing perfectly still in his cell, his blue eyes unblinking, his voice a precise instrument of seduction and menace — achieves a level of controlled terror that makes conventional horror villains look like amateurs.\n\n> \"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.\"\n\nThe scenes between Starling and Lecter are structured as exchanges — she gives him personal information, he gives her clues to catch Buffalo Bill. But the subtext is richer: they are conducting a mutual seduction, an intellectual courtship between two brilliant outsiders. Lecter respects Starling precisely because she refuses to be frightened of him, and this respect — perverse, genuine, and ultimately dangerous — is the film's emotional engine.\n\nHoward Shore's score is a masterwork of restraint. Where lesser horror scores would punctuate every scare with stingers, Shore's orchestral writing maintains a sustained atmosphere of elegant dread. The music sounds like Lecter himself: cultured, controlled, and capable of sudden violence.\n\nThe night-vision sequence — Bill stalking Starling in total darkness while she gropes blindly for a wall — is the most terrifying scene Demme ever directed. He understood that the deepest fear is not of what you can see but of what you can't."
    },
    {
      title: "A Separation",
      director: "Asghar Farhadi",
      releaseYear: 2011,
      rating: 10,
      posterUrl: "https://image.tmdb.org/t/p/w500/hReFp5M3MjdxNxOJkSGiitoarU2.jpg",
      theGood: "A masterpiece of moral complexity — every character is simultaneously right and wrong",
      theBad: "The density of cultural and legal context may require patience from Western audiences",
      review: "Asghar Farhadi's **A Separation** begins with a married couple addressing a judge directly — the camera is the court — and asking for a divorce. Simin wants to leave Iran for their daughter's future. Nader refuses to abandon his father, who has Alzheimer's. From this simple premise, Farhadi constructs a moral labyrinth so intricate that the audience, like the characters, cannot find the exit.\n\nThe central incident — an altercation between Nader and Razieh, the woman he hires to care for his father — spirals into a legal, religious, and class-based conflict that implicates everyone. Did Nader push Razieh? Did he know she was pregnant? Is Razieh telling the truth? Each revelation shifts the moral ground beneath the viewer's feet, making certainty impossible.\n\nFarhadi's great innovation is structural: he withholds information from the audience at precisely the moments when a conventional thriller would reveal it. We never see the full incident. We piece it together from contradictory testimonies, each shaped by fear, pride, religious conviction, and economic desperation. The result is not confusion but a profound experience of epistemic humility.\n\n> \"You think you can just do anything and then say 'I'm sorry'?\"\n\nThe performances are uniformly extraordinary, but Peyman Moaadi as Nader gives the film its moral center — a decent man whose small lies, each individually defensible, accumulate into something corrosive. Shahab Hosseini as Razieh's volatile husband Hodjat brings a wounded dignity that makes his rage comprehensible if not forgivable. Sarina Farhadi (the director's own daughter) as Termeh, the couple's child forced to choose between her parents, breaks your heart without a single moment of sentimentality.\n\nThe film won the Academy Award for Best Foreign Language Film and the Golden Bear at Berlin. These honors, while significant, understate its achievement. **A Separation** is not merely a great Iranian film or a great foreign film. It is one of the great films about the impossibility of justice — the recognition that in a world of competing goods and partial truths, every judgment is also an injustice."
    },
    {
      title: "City of God",
      director: "Fernando Meirelles",
      releaseYear: 2002,
      rating: 9,
      posterUrl: "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfC.jpg",
      theGood: "A visceral, kinetically edited masterwork that captures the energy and horror of Rio's favelas",
      theBad: "The sheer volume of characters and intersecting timelines can overwhelm on first viewing",
      review: "Fernando Meirelles's **City of God** opens with a chicken escaping a knife and a child caught between drug gangs and police. In that first minute, the film establishes its visual grammar: handheld cameras, rapid editing, saturated color, and a narrative velocity that never lets up for 130 minutes.\n\nSet in the Cidade de Deus housing project on the outskirts of Rio de Janeiro, the film spans three decades — the 1960s through the 1980s — tracing how a government-built neighborhood designed to relocate the poor transformed into one of the most dangerous places on earth. The story is narrated by Rocket, an aspiring photographer who survives by documenting the violence around him rather than participating in it.\n\nThe ensemble cast — drawn largely from the actual favelas — brings a raw authenticity that professional actors could never replicate. Leandro Firmino's Lil Zé, who rises from childhood psychopath to drug lord, is terrifying not because he's evil but because the environment made his trajectory feel logical. Douglas Silva's Li'l Dice, the child version of the character, gives one of the most unsettling performances by a child actor in cinema history.\n\n> \"If you run, the beast catches you; if you stay, the beast eats you.\"\n\nCésar Charlone's cinematography shifts register with each era — warm, nostalgic tones for the 1960s, grainy handheld urgency for the 1980s — creating a visual timeline that the audience absorbs unconsciously. The editing by Daniel Rezende is among the most accomplished in modern cinema: montage sequences that compress years into minutes, freeze-frames that allow the narrator to introduce dozens of characters without confusion.\n\nMeirelles avoids the twin traps of poverty cinema: he neither romanticizes the favela nor reduces its inhabitants to victims. The community contains beauty, humor, love, and creativity alongside the violence. Rocket's photography — his refusal to look away, his insistence on finding composition in chaos — mirrors the film's own aesthetic: art as survival, beauty as resistance.\n\nThe film's final revelation — that the cycle of violence simply continues, with younger and younger children picking up guns — is presented without commentary, which makes it more devastating than any editorial could. **City of God** doesn't argue against violence. It shows you what violence looks like when it becomes the only available career path."
    },
    {
      title: "Portrait of a Lady on Fire",
      director: "Céline Sciamma",
      releaseYear: 2019,
      rating: 10,
      posterUrl: "https://image.tmdb.org/t/p/w500/2LquGaFEpg0gLmMSJHbYEa4g9IY.jpg",
      theGood: "The most visually ravishing love story of the century — every frame is composed with a painter's eye",
      theBad: "The deliberately measured pacing requires surrender from viewers accustomed to more conventional romances",
      review: "Céline Sciamma's **Portrait of a Lady on Fire** takes place on a remote Breton island in 1770, where the painter Marianne (Noémie Merlant) has been commissioned to paint the portrait of Héloïse (Adèle Haenel), a young woman recently removed from a convent and destined for an arranged marriage. Héloïse refuses to sit for her portrait — a small act of rebellion in a world that allows her no others. Marianne must paint her from memory, observing her during walks along the cliffs.\n\nThe act of looking becomes the film's subject and its structure. Marianne watches Héloïse. Héloïse, gradually, watches back. The gaze — who holds it, who returns it, who flinches from it — is the vocabulary of a love story told almost entirely without words. Sciamma understands that in a world where women's desires are systematically suppressed, simply *looking* at someone you desire is a revolutionary act.\n\nClaire Mathon's cinematography uses natural light — candles, fireplaces, the grey daylight of the Breton coast — to create images of Vermeer-like luminosity. The color palette shifts as the love affair develops: cold blues and greys give way to amber warmth, then to the vivid green of a night when the lovers attend a bonfire where local women sing a hypnotic folk song. That sequence — Héloïse's dress catching fire as the women's voices swell — is one of the most transcendent moments in modern cinema.\n\n> \"Do all lovers feel they're inventing something? I do.\"\n\nSciamma makes a radical formal choice: there is almost no non-diegetic music in the film. When music appears — Vivaldi's *Summer*, heard twice — it arrives with the force of revelation. The final scene, in which Marianne watches Héloïse listen to this piece from across a concert hall, is six minutes of a single face hearing music, and it is devastating. Haenel's performance in this shot — joy, grief, memory, and loss crossing her features like weather — is one of the great feats of screen acting.\n\nThe film rejects the tragedy narrative that typically structures queer love stories. Yes, the lovers are separated by the demands of patriarchal society. But Sciamma's emphasis is not on the separation but on the sovereignty of the time they had together. Their love exists as a completed thing — a painting, a memory, a piece of music — that cannot be diminished by its ending.\n\n**Portrait of a Lady on Fire** is a masterpiece about the relationship between art and desire, about the way we preserve the people we love by looking at them carefully enough to remember."
    },
    {
      title: "Oldboy",
      director: "Park Chan-wook",
      releaseYear: 2003,
      rating: 9,
      posterUrl: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
      theGood: "A revenge thriller of staggering visual invention that culminates in one of cinema's most shocking twists",
      theBad: "The extreme violence and deeply disturbing subject matter will overwhelm many viewers",
      review: "Park Chan-wook's **Oldboy** — the middle film of his 'Vengeance Trilogy' — is the most audacious revenge narrative in cinema history. Not because of its violence, though the violence is extraordinary. Not because of its twist, though the twist is devastating. But because Park makes you root for a man's revenge and then shows you what revenge actually costs.\n\nOh Dae-su (Choi Min-sik) is imprisoned in a private cell for fifteen years. He is not told why. When he is released, he is given five days to discover the identity and motive of his captor. This quest — part detective story, part Greek tragedy — propels a narrative that accelerates toward a revelation so terrible it redefines everything that preceded it.\n\nThe corridor fight scene — a single-take, side-scrolling battle in which Oh Dae-su fights his way through a hallway of thugs armed with a claw hammer — is one of the most celebrated action sequences ever filmed. It is deliberately unglamorous: messy, exhausting, and painful. Park shoots it like a video game and scores it like a funeral, creating a cognitive dissonance that is the film in miniature.\n\n> \"Laugh, and the world laughs with you. Weep, and you weep alone.\"\n\nChoi Min-sik's performance is ferociously committed. He reportedly ate four live octopuses during filming, and his physical transformation — from bloated prisoner to lean, desperate hunter — grounds the film's more baroque elements in corporeal reality. His face in the film's climactic scene, when the truth is revealed, is a mask of pure devastation.\n\nPark's visual style — operatic, color-saturated, architecturally precise — draws equally on Hitchcock, manga, and Greek tragedy. The film's mirror images, recurring motifs of imprisonment and release, teeth and tongues, create a visual language of obsession that rewards repeated viewing.\n\nThe twist, when it comes, is not a gimmick. It is the logical, horrifying conclusion of the film's thesis: that revenge is not justice but a continuation of violence, a trap that destroys the avenger more thoroughly than any prison could. Oh Dae-su gets his revenge. The audience wishes he hadn't."
    },
    {
      title: "The Tree of Life",
      director: "Terrence Malick",
      releaseYear: 2011,
      rating: 9,
      posterUrl: "https://image.tmdb.org/t/p/w500/cXmEQEfIyFkjOVYKDBJXiw3nOXH.jpg",
      theGood: "The most ambitious American film since 2001: A Space Odyssey — a genuine attempt to depict all of existence",
      theBad: "Malick's elliptical, wordless style will exasperate viewers who need narrative structure",
      review: "Terrence Malick's **The Tree of Life** begins with the death of a nineteen-year-old boy and then shows you the birth of the universe. This is not a metaphor. The film cuts from a 1960s Texas family receiving a telegram about their son's death to the formation of galaxies, the cooling of planets, the emergence of cellular life, and the age of dinosaurs — all rendered with practical and digital effects by Douglas Trumbull, who created the visuals for *2001: A Space Odyssey*.\n\nThe cosmic sequences are not a digression. They are the film's argument: that a mother's grief and the birth of a star are events of equal significance in the order of creation. Malick, who studied philosophy at Harvard and Oxford, is making a theological claim — that grace and nature, as the mother's voiceover distinguishes them, are the two paths through existence, and every human life is a negotiation between them.\n\nBrad Pitt's Mr. O'Brien represents nature — discipline, ambition, the world's harshness. Jessica Chastain's Mrs. O'Brien represents grace — tenderness, forgiveness, beauty. Their eldest son Jack (Hunter McCracken as a child, Sean Penn as an adult) is torn between them, and his childhood in Waco, Texas — captured in golden, impressionistic fragments — becomes a universal story of innocence confronting the reality of suffering.\n\n> \"The only way to be happy is to love. Unless you love, your life will flash by.\"\n\nEmmanuel Lubezki's cinematography is among the most beautiful in cinema history. He shoots with natural light and wide-angle lenses, following children as they play, fight, discover, and wonder. The camera seems to *remember* rather than record — images float past with the quality of half-recalled sensation, the way childhood actually feels when accessed from middle age.\n\nAlexandre Desplat's score, combined with Malick's use of sacred music — Berlioz, Brahms, Górecki, Tavener — creates a sonic environment that is simultaneously intimate and cosmic. The *Lacrimosa* from Berlioz's *Requiem*, played over images of cellular division, is one of the most audacious marriages of sound and image in cinema.\n\nThe film won the Palme d'Or at Cannes, where it was both booed and given a standing ovation. This response is appropriate. **The Tree of Life** is not a film that accommodates indifference. It demands surrender or rejection, and the surrender, for those willing, is one of cinema's most profound experiences."
    },
    {
      title: "Bicycle Thieves",
      director: "Vittorio De Sica",
      releaseYear: 1948,
      rating: 10,
      posterUrl: "https://image.tmdb.org/t/p/w500/rCVOLXljzDJTIGAbcj0ZPxMWC4N.jpg",
      theGood: "The foundational work of Italian neorealism — proves that the simplest story, told with absolute honesty, can be devastating",
      theBad: "The non-professional actors occasionally deliver readings that feel awkward by modern standards",
      review: "Vittorio De Sica's **Bicycle Thieves** has the simplest possible plot: a man's bicycle is stolen, and he spends a day searching Rome for it. From this premise — so slight it would barely sustain a short film — De Sica created what many critics consider the greatest film ever made. Its power lies not in what happens but in what the search reveals about poverty, dignity, fatherhood, and the moral compromises that desperation demands.\n\nAntonio Ricci (Lamberto Maggiorani, a factory worker with no acting experience) has been unemployed for two years. He is offered a job posting bills — on the condition that he has a bicycle. His wife Maria pawns their bedsheets to retrieve the bicycle from a pawn shop. On his first day of work, it is stolen. Without the bicycle, he loses the job. Without the job, his family starves.\n\nThe search takes Antonio and his young son Bruno (Enzo Staiola, eight years old, heartbreakingly natural) through every stratum of Roman society — from a market where stolen goods are openly resold to a church where the poor attend mass for a free meal to a brothel where Antonio confronts the thief. Each location reveals a different face of postwar Italy's desperation.\n\n> \"There's a cure for everything except death.\"\n\nDe Sica and his screenwriter Cesare Zavattini made several radical choices. Non-professional actors. Real locations. Natural light. No musical score during the search sequences. These decisions, which became the tenets of Italian neorealism, strip away every layer of cinematic artifice to expose the raw emotional reality beneath.\n\nThe final scene is one of cinema's most devastating moments. Antonio, desperate, attempts to steal a bicycle himself. He is caught, humiliated in front of his son, and released by a pitying owner. Father and son walk away into the crowd, holding hands, weeping. Antonio has not just failed to recover his property; he has lost something far more precious — his son's image of him as a good man.\n\nThe genius of **Bicycle Thieves** is that it makes you feel this loss as though it were your own. De Sica proved that cinema doesn't need spectacle, stars, or special effects. It needs a man, a boy, a bicycle, and the truth."
    }
  ];

  const books = [
    {
      title: "East of Eden",
      author: "John Steinbeck",
      publishYear: 1952,
      rating: 10,
      coverUrl: "https://covers.openlibrary.org/b/id/14946017-L.jpg",
      theGood: "Steinbeck's most ambitious novel — a multigenerational epic that wrestles with the nature of good and evil",
      theBad: "The didactic philosophical passages occasionally overpower the dramatic narrative",
      review: "John Steinbeck considered **East of Eden** his magnum opus, and he was right. It is his longest, most ambitious, and most personal novel — a multigenerational saga of two families in California's Salinas Valley that retells the story of Cain and Abel across three generations, asking with each retelling whether human beings are capable of choosing good over evil.\n\nThe novel's philosophical spine is the Hebrew word *timshel* — 'thou mayest' — which Steinbeck, through the character of Lee, the Chinese-American servant-philosopher, identifies as the most important word in the Bible. God does not command Cain to triumph over sin, nor does He promise that he will. He says *thou mayest* — leaving the choice, and the responsibility, to the individual.\n\nCathy Ames, later known as Kate, is Steinbeck's most disturbing creation: a woman born without moral instinct, who uses sexuality and manipulation to destroy everyone she touches. She is a monster, and Steinbeck intends her as one — a test case for his thesis about free will. If evil can be this pure, this innate, is moral choice still possible?\n\n> \"And now that you don't have to be perfect, you can be good.\"\n\nAdam Trask, the novel's central patriarch, is Cathy's opposite — a man of such dogged goodness that his refusal to see evil nearly destroys his sons. His twins, Aron and Cal, replay the Cain and Abel dynamic with a psychological realism that transcends the allegory. Cal, the 'bad' son who desperately wants to be good, is Steinbeck's most fully realized character — a study in self-hatred and thwarted love that anticipates the tortured protagonists of the 1950s.\n\nSteinbeck wrote the novel as a letter to his young sons, wanting to leave them the story of their homeland. This paternal urgency gives the prose a warmth and directness that his more celebrated works — *The Grapes of Wrath*, *Of Mice and Men* — sometimes lack. He is writing not for critics but for his children, and the difference is palpable.\n\nThe Salinas Valley itself — golden in summer, green in winter, always vast — becomes a character as vivid as any human. Steinbeck knew this landscape the way Faulkner knew Yoknapatawpha, and his descriptions have the authority of love. **East of Eden** is his gift to the valley, to his sons, and to every reader who has wondered whether they have the power to choose who they become."
    },
    {
      title: "Pedro Páramo",
      author: "Juan Rulfo",
      publishYear: 1955,
      rating: 10,
      coverUrl: "https://covers.openlibrary.org/b/id/8305641-L.jpg",
      theGood: "In barely 120 pages, Rulfo invented a narrative technique that influenced all of Latin American literature",
      theBad: "The deliberately fragmented structure and ghostly voices can be deeply disorienting",
      review: "Juan Rulfo's **Pedro Páramo** is barely a hundred pages long and contains an entire world — a world of the dead, where voices speak from graves and time has collapsed into a single eternal present. It is the novel that made magical realism possible, the seed from which García Márquez's *One Hundred Years of Solitude* grew, and it remains more radical than any of its descendants.\n\nJuan Preciado travels to the town of Comala to find his father, Pedro Páramo. He discovers that everyone in the town is dead. He has been talking to ghosts. He didn't know, and neither did we — Rulfo withholds this revelation with the casual cruelty of a master storyteller, allowing the reader to stumble into the underworld just as Juan does.\n\nThe narrative structure is shattered — fragments of dialogue, memories, whispers, and confessions that jump between time periods and speakers without warning. Rulfo trusts the reader to assemble the story from these shards, and the act of assembly becomes the reading experience. You don't read Pedro Páramo; you reconstruct it, like an archaeologist piecing together pottery from ruins.\n\n> \"I came to Comala because I was told my father lived here, a certain Pedro Páramo. My mother told me so.\"\n\nPedro Páramo himself — the cacique, the landowner, the man who owns everything and everyone in Comala — is both a realistic portrait of Mexican rural tyranny and a mythic figure of absolute power corroded by absolute loss. His love for Susana San Juan, the only person he cannot possess, drives him to destroy the town itself in a gesture of grief so vast it becomes geological.\n\nRulfo published this novel and a single collection of short stories, then fell silent for thirty years until his death. Gabriel García Márquez said that after reading Pedro Páramo, he memorized it and could recite it backwards. Carlos Fuentes called it the greatest novel ever written in Spanish. Jorge Luis Borges placed it among the finest texts in any language.\n\nThese are not exaggerations. **Pedro Páramo** is a novel that exists at the origin point of an entire literary tradition, and it has lost none of its strangeness, none of its beauty, none of its power to make the dead speak."
    },
    {
      title: "Never Let Me Go",
      author: "Kazuo Ishiguro",
      publishYear: 2005,
      rating: 9,
      coverUrl: "https://covers.openlibrary.org/b/id/8305559-L.jpg",
      theGood: "Ishiguro achieves devastating emotional effects through what is left unsaid rather than what is spoken",
      theBad: "The characters' passivity in the face of their fate can frustrate readers who expect resistance",
      review: "Kazuo Ishiguro's **Never Let Me Go** is a novel that withholds its horror so gently that by the time you fully understand what's happening, it's too late — you're already grieving. Kathy H. narrates in a voice of such measured calm, such careful understatement, that the monstrous facts of her existence seem almost normal. This normalization is the novel's most unsettling achievement.\n\nKathy, Tommy, and Ruth grow up at Hailsham, an English boarding school where the students are encouraged to create art, are warned about the importance of health, and are never quite told the truth about why they exist. The reader pieces together the truth before the characters do: they are clones, raised as organ donors, destined to 'complete' — Ishiguro's euphemism for death — after three or four donations.\n\nThe genius of the novel is that Ishiguro refuses to write a dystopian thriller. There is no rebellion, no escape, no heroic resistance. Kathy and her friends accept their fate with the same resigned compliance that we accept our own mortality. This parallel is the novel's point: we are all, in a sense, living on borrowed time, and most of us spend that time worrying about small things — jealousy, status, whether someone likes us — rather than confronting the fundamental fact of our finitude.\n\n> \"What I'm not sure about is if our lives have been so different from the lives of the people we save.\"\n\nThe love triangle between Kathy, Tommy, and Ruth is rendered with excruciating precision. Ruth's small cruelties, Tommy's inarticulate rage, Kathy's patient, watchful devotion — these dynamics feel so real, so universally recognizable, that the science-fiction premise fades into the background. You forget they're clones. You remember they're people.\n\nThe final scene — Kathy standing at the edge of a Norfolk field, imagining that the wind might blow back to her everything she's lost — is one of the most desolate and beautiful endings in contemporary fiction. Ishiguro gives us no comfort, no redemption, only the image of a woman standing in a field, letting go.\n\n**Never Let Me Go** won no major prizes upon publication, which in retrospect seems like its own kind of injustice. Time has revealed it as one of the essential novels of the century — a quiet masterpiece about what it means to be human, written about people who aren't sure they qualify."
    },
    {
      title: "Blindness",
      author: "José Saramago",
      publishYear: 1995,
      rating: 9,
      coverUrl: "https://covers.openlibrary.org/b/id/8765816-L.jpg",
      theGood: "Saramago's unpunctuated prose style creates a reading experience as disorienting and immersive as the blindness it describes",
      theBad: "The graphic depictions of degradation and violence are deliberately difficult to endure",
      review: "José Saramago's **Blindness** begins with a man going blind at a traffic light. Within days, the blindness spreads — not a darkness but a whiteness, a luminous blankness that swallows the world. The government quarantines the afflicted in an abandoned mental hospital. Civilization collapses. Only one person retains her sight: the doctor's wife, who pretends to be blind to stay with her husband.\n\nSaramago's prose style — long, unpunctuated sentences where dialogue flows into narration without quotation marks, where speakers are identified only by description (*the girl with the dark glasses*, *the boy with the squint*) — is not a gimmick. It is the novel's formal argument. In a world without sight, individual identity dissolves. Names become meaningless. The prose enacts the loss it describes.\n\nThe quarantine sequences are among the most harrowing in modern literature. Saramago documents the regression to animality with unflinching specificity: the overflowing latrines, the food hoarded and stolen, the ward of blind men who seize control and demand the women's bodies as payment for food. These scenes are not gratuitous. They are Saramago's experiment: strip away the structures of civilization and observe what remains.\n\n> \"I don't think we did go blind, I think we are blind, Blind but seeing, Blind people who can see, but do not see.\"\n\nThe doctor's wife — unnamed, like all the characters — is the novel's moral center. Her sight is both a gift and a burden: she sees everything, including the things no one should have to see. Her decision not to close her eyes, not to look away, is Saramago's definition of courage. She becomes a guide, a protector, and ultimately a witness, which is perhaps the most important role of all.\n\nSaramago won the Nobel Prize for Literature in 1998, partly on the strength of this novel. The committee cited his ability to make *the illusory reality of the world comprehensible*. **Blindness** achieves something more specific: it makes visible the fragility of everything we take for granted — decency, hygiene, trust, community — and the terrifying speed with which these things can be lost.\n\nThe novel's final line, spoken by the doctor's wife as the blindness begins to lift, is devastating in its simplicity: *I don't think we did go blind, I think we are blind.* The epidemic was not an aberration. It was a revelation."
    },
    {
      title: "Stoner",
      author: "John Williams",
      publishYear: 1965,
      rating: 10,
      coverUrl: "https://covers.openlibrary.org/b/id/8231883-L.jpg",
      theGood: "The most quietly devastating novel in American literature — a masterpiece of radical simplicity",
      theBad: "The protagonist's passivity and the absence of dramatic incident may frustrate readers seeking action",
      review: "John Williams's **Stoner** tells the story of William Stoner, the son of Missouri dirt farmers who discovers literature as a university freshman, becomes a professor of English, teaches for forty years, endures a loveless marriage, has one transcendent love affair, raises a daughter who is taken from him, and dies. That's the plot. It is one of the most profound reading experiences available in the English language.\n\nWilliams's prose is so plain it approaches transparency. There are no pyrotechnics, no stylistic flourishes, no sentences that call attention to themselves. Every word is chosen for precision rather than beauty, and yet the cumulative effect is devastating. You read a passage about a man grading papers in his office on a winter afternoon and realize, with a shock, that you are close to tears.\n\nStoner's life, by any conventional measure, is a failure. His marriage to Edith — a woman whose emotional cruelty is the more devastating for being so quiet, so domestic, so unrelenting — is a prison from which he never escapes. His career is sabotaged by a colleague whose enmity is petty and permanent. His daughter, whom Edith uses as a weapon, grows distant and damaged.\n\n> \"He had, in odd ways, given it to every moment of his life, and had perhaps given it most fully when he was unaware of his giving.\"\n\nAnd yet. The novel insists — gently, without argument — that Stoner's life has meaning. Not the meaning of achievement or recognition, but the meaning that comes from loving something enough to devote your life to it. Stoner loves literature. He loves teaching. He loves, for a brief and luminous period, a woman named Katherine Driscoll. These loves do not save him. They make his life worth living, which is different and perhaps more important.\n\nWilliams published **Stoner** in 1965, where it sold poorly and went out of print. He died in 1994 believing it forgotten. In 2006, a new edition was published, and the novel slowly found its readers. By 2013, it was a bestseller in Europe. The story of Stoner's belated recognition mirrors the story of its protagonist: a quiet thing, overlooked for decades, that turned out to be extraordinary.\n\nI have read **Stoner** three times. Each reading has been more overwhelming than the last. It is a novel that teaches you how to live — not by showing you a model life, but by showing you an ordinary one, and proving that an ordinary life, fully inhabited, is enough."
    },
    {
      title: "The Bell Jar",
      author: "Sylvia Plath",
      publishYear: 1963,
      rating: 9,
      coverUrl: "https://covers.openlibrary.org/b/id/12818362-L.jpg",
      theGood: "Plath's only novel captures the texture of depression with an accuracy that clinical literature has never matched",
      theBad: "The autobiographical elements are so close to Plath's own life that the novel can feel uncomfortably voyeuristic",
      review: "Sylvia Plath's **The Bell Jar** was published under the pseudonym Victoria Lucas in January 1963. Plath killed herself a month later. These facts are inseparable from the novel, though the novel deserves to be read on its own merits — and those merits are considerable. It is the most precise depiction of depression in American literature, and it achieves this precision not through clinical description but through metaphor, humor, and a voice so sharp it draws blood.\n\nEsther Greenwood, a brilliant young woman spending a summer as a guest editor in New York City, begins to unravel. The unraveling is not dramatic — there are no screaming fits, no public breakdowns. Instead, Plath describes a slow, insidious disconnection: food loses its taste, sleep becomes impossible, the future appears as a fig tree whose branches represent every possible life, all of them withering simultaneously because she cannot choose just one.\n\nThe fig tree passage is one of the most quoted in modern literature, and justly so. But Plath's genius extends far beyond individual images. Her prose has a manic, observational wit that makes the descent into illness feel almost companionable. Esther notices everything — the texture of a bedspread, the particular shade of a nurse's lipstick, the precise quality of an electroshock treatment — and reports it with a dispassionate clarity that is the opposite of self-pity.\n\n> \"I felt very still and empty, the way the eye of a tornado must feel, moving dully along in the middle of the surrounding hullabaloo.\"\n\nThe bell jar of the title is Plath's metaphor for depression: a glass enclosure that descends over Esther, cutting her off from the world while leaving her visible within it. She can see people living their lives, but she cannot reach them. The air inside the bell jar grows stale. The metaphor is so apt that it has entered clinical vocabulary.\n\nThe novel's treatment of 1950s America — its suffocating expectations for women, its equation of femininity with passivity, its cheerful refusal to acknowledge mental illness — is surgically precise. Esther's breakdown is not merely personal; it is a rational response to an irrational world. Plath understood, thirty years before the phrase entered common usage, that the personal is political.\n\nPlath wrote one novel. It is enough. **The Bell Jar** says everything that needs to be said about the experience of losing one's mind, and it says it in prose that is itself the opposite of madness: controlled, elegant, and devastatingly exact."
    },
    {
      title: "The Count of Monte Cristo",
      author: "Alexandre Dumas",
      publishYear: 1844,
      rating: 9,
      coverUrl: "https://covers.openlibrary.org/b/id/12358285-L.jpg",
      theGood: "The greatest revenge narrative ever written — a thousand pages that never drag",
      theBad: "The convoluted subplots involving secondary characters can test the reader's commitment",
      review: "Alexandre Dumas's **The Count of Monte Cristo** is the ur-text of the revenge narrative — the source from which every subsequent revenge story draws, and which none has surpassed. At over a thousand pages, it is also one of the most compulsively readable novels in any language, a book that generates the particular feverish pleasure of wanting to know what happens next more than you want to sleep.\n\nEdmond Dantès, a young sailor on the verge of happiness — a captaincy, a loving father, a beautiful fiancée — is betrayed by three men motivated by jealousy, ambition, and cowardice. He is imprisoned in the Château d'If, a fortress from which no one escapes. He spends fourteen years in a cell. He meets the Abbé Faria, a fellow prisoner who educates him, teaches him languages, science, and swordplay, and reveals the location of an immense treasure on the island of Monte Cristo.\n\nDantès escapes — the escape sequence is one of literature's great set pieces — recovers the treasure, and reinvents himself as the Count of Monte Cristo: a figure of mysterious wealth, vast knowledge, and implacable purpose. He then proceeds, over several hundred pages, to systematically destroy the three men who ruined him.\n\n> \"All human wisdom is contained in these two words: wait and hope.\"\n\nDumas's genius — often underestimated because of the novel's popularity — lies in his understanding that revenge is not a single act but an architecture. The Count's plots are elaborate, patient, and interconnected, each one exploiting the specific weakness of its target. Fernand's vanity. Danglars's greed. Villefort's hypocrisy. The Count doesn't just punish them; he uses their own natures as the instruments of their destruction.\n\nThe novel's deeper question — whether revenge ultimately satisfies or corrupts its pursuer — emerges gradually from beneath the narrative's adventure-story surface. The Count begins as a righteous avenger and slowly becomes something colder, something that frightens even him. The collateral damage of his schemes — innocent people wounded, young lives disrupted — forces him to confront the possibility that justice and vengeance are not the same thing.\n\nDumas wrote the novel as a serial, publishing installments over two years, and the serial structure gives it its extraordinary momentum. Every chapter ends with a hook. Every revelation opens a new question. The reader is drawn forward as irresistibly as Dantès is drawn toward his enemies.\n\n**The Count of Monte Cristo** is not great literature in the way that Tolstoy or Dostoevsky wrote great literature. It is something else entirely: a perfect story, told with perfect skill, about the oldest human desire — to make the world fair. That it concludes by questioning whether fairness is possible makes it not just entertaining but wise."
    },
    {
      title: "The Remains of the Day",
      author: "Kazuo Ishiguro",
      publishYear: 1989,
      rating: 10,
      coverUrl: "https://covers.openlibrary.org/b/id/12951431-L.jpg",
      theGood: "The most perfectly controlled first-person voice in modern fiction — every sentence is a masterpiece of repression",
      theBad: "Stevens's emotional constipation can be maddening, which is precisely Ishiguro's intention",
      review: "Kazuo Ishiguro's **The Remains of the Day** is narrated by Stevens, an English butler who has spent his entire life in service to Lord Darlington — a man who, it gradually emerges, was a Nazi sympathizer. Stevens is driving through the English countryside in 1956, ostensibly to recruit a former housekeeper named Miss Kenton, and he uses the journey to reflect on his career, his employer, and the life he chose not to live.\n\nStevens's voice is one of the great achievements of modern fiction. He speaks in a register of impeccable formality that is simultaneously comical and heartbreaking. Every sentence is a small act of self-deception. When he describes Miss Kenton's departure from Darlington Hall, he uses the language of staffing logistics to describe what was clearly heartbreak. When he discusses Lord Darlington's 'errors of judgment,' he uses the vocabulary of professional discretion to avoid confronting his own complicity in evil.\n\n> \"Indeed — why should I not admit it? — at that moment, my heart was breaking.\"\n\nThe novel's central relationship — between Stevens and Miss Kenton — is one of literature's great unconsummated love stories. Their interactions are conducted through the elaborate rituals of household management: discussions of silver polish, flower arrangements, staff schedules. But beneath this professional surface, a genuine and mutual attraction simmers. Miss Kenton sees through Stevens's formality and loves the man underneath. Stevens sees Miss Kenton's warmth and retreats from it, choosing duty over love with a consistency that is heroic and devastating.\n\nIshiguro's treatment of Lord Darlington is subtle and damning. Stevens's loyalty to his employer — his refusal to acknowledge Darlington's anti-Semitism, his dismissal of the Jewish maids on Darlington's orders — raises the novel's most uncomfortable question: is dignity in service compatible with moral responsibility? Can you be a good butler and a good person simultaneously?\n\nThe final scene — Stevens sitting on a pier at dusk, watching the lights come on along the seafront, weeping quietly as he acknowledges for the first and only time that he has wasted his life — is one of the most moving passages in English literature. Ishiguro earns every tear by withholding emotion for 240 pages and then releasing it in a single, devastating paragraph.\n\n**The Remains of the Day** won the Booker Prize in 1989. It deserved it. But the novel's true prize is the one it gives its reader: the ability to recognize the Stevens in themselves — the part that chooses safety over love, duty over desire, the comfortable lie over the uncomfortable truth — and to decide, while there is still time, to choose differently."
    }
  ];

  console.log('Seeding additional Movies...');
  for (const m of movies) {
    await prisma.movieReview.create({
      data: {
        title: m.title,
        director: m.director,
        releaseYear: m.releaseYear,
        rating: m.rating,
        posterUrl: m.posterUrl,
        theGood: m.theGood,
        theBad: m.theBad,
        review: m.review,
        authorId: userId
      }
    });
    console.log(`  ✓ ${m.title}`);
  }

  console.log('\nSeeding additional Books...');
  for (const b of books) {
    await prisma.bookReview.create({
      data: {
        title: b.title,
        author: b.author,
        publishYear: b.publishYear,
        rating: b.rating,
        coverUrl: b.coverUrl,
        theGood: b.theGood,
        theBad: b.theBad,
        review: b.review,
        authorId: userId
      }
    });
    console.log(`  ✓ ${b.title}`);
  }

  console.log('\n🎬📚 Batch 4 seeded successfully!');

  const movieCount = await prisma.movieReview.count();
  const bookCount = await prisma.bookReview.count();
  console.log(`Total: ${movieCount} movies, ${bookCount} books`);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
